### ISSUE TITLE
LoadBalancer for external databases?

### ISSUE THREAD

**Issue by kvaps** [wireapp/wire-server-deploy#196]
Hi, I've deployed wire-server with [external databases](https://docs.wire.com/how-to/install/monitoring.html) using official installation guide, then I created endpoints for these external services:

```yaml
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "cassandra-external"
spec:
  clusterIP: None
  ports:
    - name: "cassandra"
      protocol: "TCP"
      port: 9042
      targetPort: 9042
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "cassandra-external"
subsets:
  - addresses:
      - ip: "10.9.8.11"
    ports:
      - port: 9042
        name: "cassandra"
  - addresses:
      - ip: "10.9.8.12"
    ports:
      - port: 9042
        name: "cassandra"
  - addresses:
      - ip: "10.9.8.13"
    ports:
      - port: 9042
        name: "cassandra"
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "elasticsearch-external"
spec:
  clusterIP: None
  ports:
    - name: "elasticsearch"
      protocol: "TCP"
      port: 9200
      targetPort: 9200
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "elasticsearch-external"
subsets:
  - addresses:
      - ip: "10.9.8.21"
    ports:
      - port: 9200
        name: "cassandra"
  - addresses:
      - ip: "10.9.8.22"
    ports:
      - port: 9200
        name: "cassandra"
  - addresses:
      - ip: "10.9.8.23"
    ports:
      - port: 9200
        name: "cassandra"
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "minio-external"
spec:
  clusterIP: None
  ports:
    - name: "minio"
      protocol: "TCP"
      port: 9000
      targetPort: 9000
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "minio-external"
subsets:
  - addresses:
      - ip: "10.9.8.31"
    ports:
      - port: 9000
        name: "minio"
  - addresses:
      - ip: "10.9.8.32"
    ports:
      - port: 9000
        name: "minio"
  - addresses:
      - ip: "10.9.8.33"
    ports:
      - port: 9000
        name: "minio"
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "redis-external"
spec:
  clusterIP: None
  ports:
    - name: "elasticsearch"
      protocol: "TCP"
      port: 6379
      targetPort: 6379
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "redis-external"
subsets:
  - addresses:
      - ip: "10.9.8.41"
    ports:
      - port: 6379
        name: "redis"
  - addresses:
      - ip: "10.9.8.42"
    portsж
      - port: 6379
        name: "redis"
  - addresses:
      - ip: "10.9.8.43"
    ports:
      - port: 6379
        name: "redis"
```

After, I found out that official helm charts also using the same logic:
- [cassandra-external](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/cassandra-external/templates/endpoint.yaml)
- [elasticsearch-external](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/elasticsearch-external/templates/endpoint.yaml)
- [minio-external](https://github.com/wireapp/wire-server-deploy/blob/develop/charts/minio-external/templates/endpoint.yaml)

Problem is that created manually endpoints have no any healthcheck mechanism and they are not high available by the default, thus there should be some logic implemented on the client side or another load balancer. 

My question does wire-server this logic implemented, or should I to use some external loadbalancer eg. harpoxy to route the traffic to these services?
