### ISSUE TITLE
getting external smtp to work - smtpUsername to username?

### ISSUE THREAD

**Issue by tofutim** [wireapp/wire-server-deploy#264]
Hi, I have been having a hard time getting email working on the demo server (https://github.com/wireapp/wire-docs/issues/56). In particular, I am attempting to use authenticated smtp. In `wire-server-deploy/charts/brig/templates/configmap.yaml`, I see
```
        smtpCredentials:
          username: {{ .smtp.username }}
          password: {{ .smtp.passwordFile }}
```
yet in wire-server/services/brig/src/Brig/Options.hs
```
data EmailSMTPCredentials = EmailSMTPCredentials
  { -- | Username to authenticate
    --   against the SMTP server
    smtpUsername :: !Text,
    -- | File containing password to
    --   authenticate against the SMTP server
    smtpPassword :: !FilePathSecrets
  }
  deriving (Show, Generic)

instance FromJSON EmailSMTPCredentials
```
it gets read in App.hs
```
      smtpCredentials <- case Opt.smtpCredentials s of
        Just (Opt.EmailSMTPCredentials u p) -> do
          pass <- initCredentials p
          return $ Just (SMTP.Username u, SMTP.Password pass)
        _ -> return Nothing
```
where I think there will be a mismatch between smtpUsername and username, and smtpPassword and password, maybe why I have the error
```
service: user error (AesonException "Error in $.emailSMS.email.smtpCredentials: parsing Brig.Options.EmailSMTPCredentials(EmailSMTPCredentials) failed, key \"smtpUsername\" not found")
```
for my deploy values.txt, I am now using
```
    smtp:
      host: smtp.gmail.com # change this if you want to use your own SMTP server
      port: 587        # change this
      connType: tls # change this. Possible values: plain|ssl|tls
      username: xxxxx@gmail.com
      passwordFile: /etc/wire/brig/secrets/smtp-password.txt
```

I'd like to test out my theory, but haven't yet explored compiling brig on this end. Any thoughts much appreciated. I think perhaps I can make the changes in configmap.yaml and
```
./bin/update.sh ./charts/<chart-name> # this will clean and re-package subcharts
helm install charts/<chart-name> # specify a local file path
```

**Update.** I tried changing the configmap and then
```
helm dependency update charts
```
from /mnt/wire-server-deploy, then
```
helm upgrade --install wire-server charts/wire-server -f wire-server/values.yaml -f wire-server/secrets.yaml
```
this time, a new error
```
  error, called at src/Brig/SMTP.hs:59:5 in brig-1.35.0-75AXQWXBSmK9R80VH6rqDH:Brig.SMTP
```
but I think this time username and password were read in.

**Update 2.** This time the error was from Gmail!
![image](https://user-images.githubusercontent.com/157766/81899554-fdc9f100-956f-11ea-8ccf-5ccb84e54748.png)
after making this change email works...
