### ISSUE TITLE
Audio/Video call issue.

### ISSUE THREAD

**Issue by rahulit1991** [wireapp/wire-server-deploy#283]
Hello guys,

i have setup one turn server ```turn01.example.io``` on separate VM. Also i make proper configuration on wire-server/value.yml for turn server:

```
brig:
    config:
      - some configuration
    turnStatic:
      v1:
      - turn:turn01.example.io.io:3478
      v2:
      - "turn:turn01.example.io:3478"
      - "turn:turn01.example.io::80?transport=tcp"
      - "turns:turn01.example.io:443?transport=tcp"
```

after successful configuration. when run test for restund server using kubernetes proxy with localhost and my system UUID, it shows localhost rather than my turn server endpoints.please find in screenshot.

![image](https://user-images.githubusercontent.com/64314085/84225598-39b78e00-aafd-11ea-82aa-22234616b944.png)

can you help why i am facing this issue?

Thanks
