### ISSUE TITLE
SMS configuration issues with wire server deploy script

### ISSUE THREAD

**Issue by ramesh8830** [wireapp/wire-server-deploy#285]
Hi,

I am trying to deploy wire server using below SMS configuration and getting below error when I set smsSender as number in values.yaml file.

```
    emailSMS:
      general:
        emailSender: mail@example.com # change this
        smsSender: "+18123456789" # change this if SMS support is desired
```

Getting below error for brig pod.

`service: user error (AesonException "Error in $.emailSMS.general.smsSender: parsing Text failed, expected String, but encountered Number")`

Please help me.

**Comment by rahulit1991** [comment]
facing same issue with twilio. first i set number but it through an error above error. After that i allowed alphanumeric id in account. but still facing same issue.

**Comment by mheinzel** [comment]
Did you make sure to put quotes around the number? Otherwise, YAML will parse it as a number, not a string.

For example above, it says `smsSender: "+18123456789"`, which works for me, but without the quotes `smsSender: +18123456789`, I get the same error you pasted above.

**Comment by rahulit1991** [comment]
yes. i tried with both. did not work.

**Comment by ramesh8830** [comment]
> Did you make sure to put quotes around the number? Otherwise, YAML will parse it as a number, not a string.
> 
> For example above, it says `smsSender: "+18123456789"`, which works for me, but without the quotes `smsSender: +18123456789`, I get the same error you pasted above.

I tried with double quotations and didn't work.

**Comment by lucendio** [comment]
Where did you try the quotation? In Helm's values.yaml or in the resulting ConfigMap that is consumed by Brig?

**Comment by ramesh8830** [comment]
I tried it on the values.yaml inside wire-server

**Comment by lucendio** [comment]
Okay, that wont work, see https://github.com/wireapp/wire-server-deploy/blob/develop/charts/brig/templates/configmap.yaml#L77.

I suggest to add the quotes directly in the ConfigMap (`data.brig.yaml`). Dont forget to trigger the pods so they get recreated (w/o redeploying!),  so that they pick up the changes in the ConfigMap. If that works, we need to adjust the brig chart.

**Comment by ramesh8830** [comment]
Thank you @lucendio . That worked by adding quotes in the ConfigMap file.

**Comment by rahulit1991** [comment]
@lucendio , i take latest pull and now i can see new changes made in configMap.yml. " **smsSender: {{ .emailSMS.general.smsSender | quote }}"**.

I tried with delete ```helm delete --purge wire-server``` and update configuration with ```helm upgrade --install wire-server wire/wire-server -f values.yaml -f secrets.yaml```
 But still i am facing same issue as pod is crashed with following error:

```
   service: user error (AesonException "Error in $.emailSMS.general.smsSender: parsing Text failed, expected String, but encountered Number")

```
Here is my configuration in values.yml

```
emailSMS:
      general:
        emailSender: email@example.com # change this
        smsSender: "+177*****663" # change this if SMS support is desired
    smtp:
      host: demo-smtp # change this if you want to use your own SMTP server
      port: 25        # change this
      connType: plain # 
```

can you please check where i am wrong here or an issue.
