### ISSUE TITLE
Question: [SMTP not working and Problem with external SMTP]

### ISSUE THREAD

**Issue by mtahle** [wireapp/wire-server-deploy#319]
### Basic information

* On-premises: 
 no
* Cloud-Provider: 
 IBM
* Installation type:  DEMO
* Kubernetes version:  
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"b4455102ef392bf7d594ef96b97a4caa79d729d9", GitTreeState:"clean", BuildDate:"2020-06-17T11:39:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9+IKS", GitCommit:"dbe4e8a5c169e0a6a8a9b7b183561fa61e161985", GitTreeState:"clean", BuildDate:"2020-07-16T01:30:57Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

* Helm version: 
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

* Installed with Kubespray:  no
* (Helm) Charts version: 
  version: 0.114.0

* List of installed top-level charts:  
databases-ephemeral 
fake-aws  
nginx-ingress-controller
nginx-ingress-services
smtp
wire-server 
* Other related technologies + version: 
N/A

### How did you install Wire?

 yes in one step only and as described in this issue  [](https://github.com/wireapp/wire-server-deploy/issues/246#issuecomment-661296424)

### Question

Hello,

I have a problem when using demo-smtp, I keep getting this message `SOMETHING WENT WRONG. PLEASE CONTACT YOUR TEAM ADMINISTRATOR FOR DETAILS (ERROR 6).` when trying to register  a new user, I have checked brig logs and I found this :

`{"request":"e5ee5a502acfb9eb919f5967b1e5fc70","msgs":["E","user error (cannot execute command RCPT \"email@company.com\", expected reply code 250, but received 550 relay not permitted\r\n)"]}
`
I tired to change to use external SMTP in values.yaml and I make it like this:

```
smtp:
      host: smtp.gmail.com # change this if you want to use your own SMTP server
      port: 587        # change this
      connType: tls # change this. Possible values: plain|ssl|tls
      username: xxxxx@gmail.com
      passwordFile: /etc/wire/brig/secrets/smtp-password.txt
```
also changed the secrets.yaml:

```
brig:
  secrets:
    smtpPassword: {gmail_password}
```
but this time the brig pod is entering in CrashLoopBackOff status and keep restarting 

so how to this the right way? what I'm missing?
